### ISSUE TITLE
arrays in addition to objects

### ISSUE THREAD

**Issue by travi** [bryanrsmith/eslint-plugin-no-unused-vars-rest#2]
have you considered extending this to handle array destructuring in the same way?

**Comment by bryanrsmith** [comment]
I thought about it, but it seems unnecessary with arrays because you can use sparse destructuring syntax.

```js
const [,a,,b] = [1, 2, 3, 4, 5];
console.log(a) // 2
console.log(b) // 4
```

Sorry for the slow response.

**Comment by travi** [comment]
no worries about response timing. 

i remembered that you could omit the ones you were skipping after posting this. i think being able to specify names for the skipped entries would potentially be more readable, but omitting them does cover my need for now.
