### ISSUE TITLE
Now in eslint

### ISSUE THREAD

**Issue by cwmanning** [bryanrsmith/eslint-plugin-no-unused-vars-rest#3]
I added this plugin to a project earlier today (thank you for filling the gap!) before realizing that this is an option in eslint now:

http://eslint.org/docs/rules/no-unused-vars#ignorerestsiblings

Would you consider adding to the README for others who might land here in the future?

**Comment by bryanrsmith** [comment]
Cool! I didn't know it had been added; thanks for letting me know. I'll add a note to the README. I could also deprecate the npm package, but it might be annoying for folks on older versions of ESLint. Maybe I'll wait a little while before doing that.
